# Generated by Django 6.0 on 2026-01-07 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngresoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(choices=[('UNITARIO', 'Unitario'), ('PACK', 'Pack'), ('GRANEL', 'Granel')], max_length=10)),
                ('unidad_base', models.CharField(choices=[('UNIDAD', 'Unidad'), ('KG', 'Kilogramo'), ('PACK', 'Pack'), ('CAJA', 'Caja')], max_length=10)),
                ('stock_actual_base', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('unidades_por_pack', models.IntegerField(blank=True, null=True)),
                ('kg_por_caja', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoStockDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_base', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ingresostock')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
    ]
