# Generated by Django 6.0 on 2026-01-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_base',
            field=models.CharField(choices=[('UNIDAD', 'Unidad'), ('PACK', 'Pack'), ('KG', 'Kg')], max_length=10),
        ),
    ]
