# Generated by Django 6.0 on 2026-01-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='stock_base',
        ),
        migrations.AddField(
            model_name='presentacion',
            name='kg_por_caja',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='unidades_por_pack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual_base',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
