# Generated by Django 6.0 on 2026-01-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_presentacion_stock_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='cantidad_base',
        ),
    ]
