# Generated by Django 6.0 on 2026-01-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresostockdetalle',
            name='ingreso',
        ),
        migrations.RemoveField(
            model_name='ingresostockdetalle',
            name='producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.DeleteModel(
            name='IngresoStock',
        ),
        migrations.DeleteModel(
            name='IngresoStockDetalle',
        ),
    ]
