# Generated by Django 6.0 on 2026-01-09 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_unidad_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresostock',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('REMITO', 'Remito'), ('RECEPCION', 'Recepción'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='ingresostock',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingresostock',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ingresostock',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
