# Generated by Django 6.0 on 2026-01-06 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresostockdetalle',
            name='ingreso',
        ),
        migrations.RemoveField(
            model_name='ingresostockdetalle',
            name='producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria'),
        ),
        migrations.DeleteModel(
            name='IngresoStock',
        ),
        migrations.DeleteModel(
            name='IngresoStockDetalle',
        ),
    ]
