# Generated by Django 6.0 on 2026-01-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_ingresostockdetalle_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(blank=True, help_text='Ej: 350ml, 1L, 6 pack, 2L', max_length=100, null=True),
        ),
    ]
