# Generated by Django 6.0 on 2026-01-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_presentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='presentacion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
