# Generated by Django 6.0 on 2026-01-06 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_change_categoria_to_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='kg_por_caja',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='margen_ganancia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_base',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_base',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidades_por_pack',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unidad', models.CharField(choices=[('ml', 'Mililitros'), ('l', 'Litros'), ('g', 'Gramos'), ('kg', 'Kilogramos'), ('un', 'Unidad')], max_length=5)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('codigo_barra', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='inventario.producto')),
            ],
        ),
    ]
