# Generated by Django 6.0 on 2026-01-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_simplify_producto_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(default='TEMP', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='kg_por_caja',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_base',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_base',
            field=models.CharField(choices=[('UNIDAD', 'Unidad'), ('KG', 'Kilogramo')], default='UNIDAD', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_pack',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
