# Generated by Django 6.0 on 2026-01-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_restore_producto_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_base',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_base',
            field=models.CharField(choices=[('UNIDAD', 'Unidad'), ('KG', 'Kilogramo')], max_length=10),
        ),
    ]
