# Generated by Django 6.0 on 2026-01-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo_accion',
            field=models.CharField(choices=[('APERTURA_CAJA', 'Apertura de Caja'), ('CIERRE_CAJA', 'Cierre de Caja'), ('VENTA', 'Venta'), ('INGRESO_STOCK', 'Ingreso de Stock'), ('STOCK_BAJO', 'Stock Bajo'), ('CREACION_PRODUCTO', 'Creación de Producto'), ('EDICION_PRODUCTO', 'Edición de Producto'), ('CREACION_CATEGORIA', 'Creación de Categoría'), ('EDICION_CATEGORIA', 'Edición de Categoría'), ('ELIMINACION_CATEGORIA', 'Eliminación de Categoría'), ('CREACION_REGISTRO', 'Creación de Registro'), ('EDICION_REGISTRO', 'Edición de Registro'), ('ELIMINACION_REGISTRO', 'Eliminación de Registro')], max_length=30),
        ),
    ]
