# Generated by Django 6.0 on 2026-01-07 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='caja.caja'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo_accion',
            field=models.CharField(choices=[('APERTURA_CAJA', 'Apertura de Caja'), ('CIERRE_CAJA', 'Cierre de Caja'), ('VENTA', 'Venta'), ('INGRESO_STOCK', 'Ingreso de Stock'), ('CREACION_PRODUCTO', 'Creación de Producto'), ('EDICION_PRODUCTO', 'Edición de Producto'), ('CREACION_CATEGORIA', 'Creación de Categoría')], max_length=30),
        ),
    ]
