# Generated by Django 6.0 on 2026-01-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventadetalle',
            name='cantidad_base',
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='unidad_venta',
        ),
    ]
