# Generated by Django 6.0 on 2026-01-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_debito_to_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='cantidad_base',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='cantidad_ingresada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='subtotal',
            field=models.IntegerField(),
        ),
    ]
