# Generated by Django 6.0 on 2026-01-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_vendido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_debito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ganancia_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('abierta', models.BooleanField(default=True)),
                ('hora_apertura', models.DateTimeField()),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
