# Generated by Django 6.0 on 2026-01-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='ganancia_diaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_inicial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_debito',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_efectivo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_transferencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_vendido',
            field=models.IntegerField(default=0),
        ),
    ]
