# Generated by Django 6.0 on 2026-01-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='hora_apertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
