# Generated by Django 6.0 on 2026-01-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_caja_ganancia_diaria_alter_caja_monto_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='ganancia_diaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_vendido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
